import { useState } from 'react';
import { ArrowUpRight, ArrowLeft, ArrowRight } from 'lucide-react';
import { projects } from '../data/portfolio';
import SectionTitle from '../components/SectionTitle';
const stories=[
  {question:'How can following the game feel effortless?',answer:'Bring live scores, schedules, standings, and team statistics into one centralized experience.',focus:'Working with sports data, API integration, and an interface built for exploration.'},
  {question:'How can a digital tool support a daily practice?',answer:'Bring prayer times, duas, and Islamic calendar features together in an accessible mobile and web experience.',focus:'Connecting useful information with thoughtful, everyday interface design.'},
  {question:'How can finding a car become a clearer decision?',answer:'Give visitors a way to browse, filter, and compare vehicles through a focused search interface.',focus:'Search interactions, JavaScript, and organizing information around the user.'},
  {question:'What can we learn by taking technology into the air?',answer:'Explore flight automation, aerial technology, and camera systems using DJI platforms.',focus:'Understanding how hardware and software work together in aerial systems.'},
  {question:'How can money management feel more approachable?',answer:'Explore tracking and managing money through a clean demo application.',focus:'Finance interface design and practical JavaScript development.'},
];
export default function Projects(){const [active,setActive]=useState(0),p=projects[active],s=stories[active]||{question:'How can an idea become useful?',answer:p.description,focus:'A portfolio project shaped through research, prototyping, and iteration.'};const host=p.link?new URL(p.link).hostname:'PROJECT STUDY';return <section id="projects" className="section projects-section"><SectionTitle number="02" eyebrow="SELECTED BUILDS" description="Real ideas. Working interfaces. A closer look at how I turn curiosity into something you can use.">Built to be<br/><em>experienced.</em></SectionTitle><div className="project-workbench"><div className="project-index" role="tablist" aria-label="Select a project">{projects.map((p,i)=><button id={`project-tab-${i}`} key={p.title} role="tab" aria-selected={i===active} aria-controls="project-detail" onClick={()=>setActive(i)}><span>{String(i+1).padStart(2,'0')}</span>{p.title}<ArrowUpRight size={16}/></button>)}</div><article id="project-detail" role="tabpanel" aria-labelledby={`project-tab-${active}`} className="project-detail">{p.image&&<div className="project-image"><div className="browser-bar"><span>● ● ●</span><span>{host}</span><ArrowUpRight size={12}/></div><img src={p.image} alt={`${p.title} project interface`} loading="lazy" width="1200" height="700"/><span className="image-caption">PROJECT ARCHIVE / {String(active+1).padStart(2,'0')}</span></div>}<div className="project-summary"><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><h3>{p.title}</h3><p>{p.description}</p><div className="case-study"><div><span className="eyebrow">THE QUESTION</span><h4>{s.question}</h4></div><div><span className="eyebrow">THE APPROACH</span><p>{s.answer}</p><p className="project-focus">{s.focus}</p></div></div>{p.link&&<a className="primary-link" href={p.link} target="_blank" rel="noreferrer">Open project <ArrowUpRight size={17}/></a>}<div className="project-arrows"><button aria-label="Previous project" onClick={()=>setActive((active+projects.length-1)%projects.length)}><ArrowLeft size={18}/></button><span>{String(active+1).padStart(2,'0')} / {String(projects.length).padStart(2,'0')}</span><button aria-label="Next project" onClick={()=>setActive((active+1)%projects.length)}><ArrowRight size={18}/></button></div></div></article></div><div className="process-line"><span className="eyebrow">HOW I BUILD</span>{['Idea','Plan','Design','Code','Test','Deploy','Improve'].map((p,i)=><span key={p}>{i>0&&<b>↗</b>}{p}</span>)}</div></section>;}
